function projs = givePprojRAND2()
    projs = {{RandomPOVM(2,2),RandomPOVM(2,2),RandomPOVM(2,2)}, ...
                {RandomPOVM(2,2),RandomPOVM(2,2)}, ...
                {RandomPOVM(2,2),RandomPOVM(2,2)}};
end